Jam - Add dev tool to diagnose mags added via wells
CBATeam/CBA_A3 pull request #1601
Opened 2023-09-15 04:42 UTC by PabstMirror

2023-09-16 22:38 UTC, rautamiekka requested changes

2023-09-16 22:38 UTC, rautamiekka commented on addons/jam/dev_diagnoseMagWells.sqf
> +_prefix = toLower _prefix;
```suggestion
_prefix = toLowerANSI _prefix;
```

2024-03-31 20:45 UTC, jonpas commented
@PabstMirror Good to merge?

2024-03-31 21:12 UTC, PabstMirror commented
yeah, I doubt many will ever use this, but it might be nice to have in the release

2024-03-31 21:34 UTC, jonpas approved these changes

2024-03-31 21:35 UTC, merged